AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Express App Serverless on AWS

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 256

Resources:
  TaskAttachmentsBucket:
    Type: AWS::S3::Bucket

  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tasks
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ExpressAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src/lambda.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
        - S3CrudPolicy:
            BucketName: !Ref TaskAttachmentsBucket
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksTable
          ATTACHMENTS_BUCKET: !Ref TaskAttachmentsBucket
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "Express API URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
